OPENWEATHER_API_KEY = "f52dfb94f347842c450782e1aa663875"
Google_Search_API_KEY = "AIzaSyC45YIf7zRRcvxz4VJ9jAvVtIE_6cykUWs"
GOOGLE_CSE_ID = "200" # Seu Custom Search Engine ID
GEMINI_API_KEY = "AIzaSyABUWaC8t4I7JZ-ZwJhuWEaEDZGF7BfS2M"
