OPENWEATHER_API_KEY = "c4cb96fc4a697d3403b9f1ca70a74020"
Google_Search_API_KEY = "AIzaSyC45YIf7zRRcvxz4VJ9jAvVtIE_6cykUWs"
GOOGLE_CSE_ID = "200" # Seu Custom Search Engine ID
GEMINI_API_KEY = "AIzaSyABUWaC8t4I7JZ-ZwJhuWEaEDZGF7BfS2M"
